### PR TITLE
get symfony ^2.7 compatibility and add bot-detect 2.0

### PR DESCRIPTION
**Pull request by jdeniau**
As you bundle is stil compatible with SF 2.7+, I added the compatibility back

And as bot-detect package does not break things that will break this package, I added the two version in it (the breaking things will just not install bot-detect 2.x version that's all)

### CODE REVIEW

**Comment by jdeniau** [comment]
Lol I just saw that I alre

**Comment by jdeniau** [comment]
Lol I just saw that I opened a similar PR a couple of months ago, I will close #21 as this PR supersed it

**Comment by lennerd** [comment]
Thanks for your PR! Will have to fix the Travis setup and unit tests similar to last fixes in the `vipx-bot-detect` library.

**Comment by COil** [comment]
Status about this? I notices 1.x is still used and package is marked as outdated by composer.

**Comment by lennerd** [comment]
Sorry. Still really occupied. You can give it a try, if you like. 😉

**Comment by COil** [comment]
What do you mean I don't have merge rights.

**Comment by jdeniau** [comment]
@COil I think he said that you can require to use my branch like explained [here](https://getcomposer.org/doc/articles/aliases.md#require-inline-alias) and tell if it does work for you.

**Comment by lennerd** [comment]
Not quite. Sorry for being a little curt. 😉 Travis is not running correctly. It would be awesome if somebody could fix the testing setup and create a seperate PR for this. As soon as this is done, we could simply rebase this PR from @jdeniau and merge it.

1. PR for fixing the Travis setup (mainly usage of new namespaced testing classes) 
2. PR for supporting different versions of Symfony

@COil Is it more clear now? 

@jdeniau It would be great if you could also add the new Symfony versions to the Travis testing matrix. See the `.travis` file in the `vipx-bot-detect` library for more infos, especially the `env` usage inside the test commands: https://github.com/lennerd/vipx-bot-detect/blob/master/.travis.yml#L14-L18

**Comment by lennerd** [comment]
@jdeniau … and it would be great if you could also add Symfony 4 to the mix, so we expand the coverage to all maintained versions.

**Comment by jdeniau** [comment]
Just rebased this upon #28.

You probably see all the modifs from #28 here too, but once it's merged, I will update this.

**Comment by lennerd** [comment]
Fixed in #29.

**Pull request closed without merging**
