### PR TITLE
Added a test action (1st draft)

### PR DESCRIPTION
**Pull request by COil**
Hi @lennerd,

Here is a first draft, two questions:

- Do you think it worths creating a basic form instead of passing the user agent via get ?
- Do you think it worths also testing ips ?

++ COil  

#11

### CODE REVIEW

**Comment by lennerd** [comment]
I'm again in a bit of work at the moment and will try to come back to this PR as soon as possible.
For now I would like you to add a section to the documentation, so others know how to enable this.

**Comment by COil** [comment]
@lennerd  ping, Ok for the doc. Do we add a form ? It's seems better than using a get parameter for user experience.

**Comment by lennerd** [comment]
I rethought this a bit. What do you think about a command line extension? Instead of adding a template, we could use the easy to extend command line interface comming with Symfony to test certain bots metadata. This way the user does not need to pollute his environment both in development and later in production by adding some router configuration.

**Comment by COil** [comment]
Seems like a good idea.

**Comment by lennerd** [comment]
Do you have the time, to try something with the console?

**Comment by COil** [comment]
Yes I'll have a look this week.

**Comment by lennerd** [comment]
Any progress here?

**Comment by COil** [comment]
Hum sorry I have forgot. I'll try this week if I can find time.

**Comment by lennerd** [comment]
No problem. Happy that you try to help.

**Comment by COil** [comment]
@lennerd Can you close this one ?

**Pull request closed without merging**
