### PR TITLE
Fixes for Symfony 3.0

### PR DESCRIPTION
**Pull request by samdjstevens**
So I actually tried using this today in my Symfony 3.0 project and found a couple of small fixes that needed to be made. 

Fix incorrect class name in services definition, update chanted getKey method to getSecret, update documentation examples.

### CODE REVIEW

**Comment by lennerd** [comment]
This need to be covered by unit tests. What do you think?

**Comment by samdjstevens** [comment]
The only change I can see benefiting from/being able to have a unit test would be testing the `fromAnonymousToken` method on the `BotToken` class, as the other changes are documentation/configuration. Thoughts?

**Comment by lennerd** [comment]
Yes, you are right. Can you add a small test to the test file of the `BotToken`? Ask if you need any help with that.

**Comment by samdjstevens** [comment]
No problem, unit test added!

**Comment by lennerd** [comment]
90% yeah!

**Pull request merged**
